### PR TITLE
fix: restore canonical vault refs detection

### LINKED ISSUE #1189: Fix Secrets page 'Missing' detection (support canonical Vault refs)
# Fix Secrets page "Missing" detection (support canonical Vault refs)

## User request
The Secrets page should display "Missing" secrets. "Missing" means a secret is referenced in the Graph but does not exist in Vault. This feature worked previously but has regressed and no longer shows missing secrets.

## Research summary (Emerson Gray)
- The UI determines Missing via a union of:
  - Required secrets from the persisted graph, and
  - Available secrets discovered from Vault
- Root cause: the collector that extracts Vault references from the graph only recognizes the legacy reference shape `{ source: 'vault', value: string }` and ignores the new canonical shape `{ kind: 'vault', mount?, path, key }` (including when nested under `{ source: 'vault', value: { kind: 'vault', ... } }`). After graph migration to canonical refs, the Required set becomes empty, so nothing is marked Missing.

### Key code paths
- Required (graph): `packages/platform-ui/src/api/modules/graph.ts` → `computeRequiredKeys` (uses `collectVaultRefs`)
- Vault discovery: `packages/platform-ui/src/features/secrets/utils/flatVault.ts` → `discoverVaultKeys`
- Union and status: `packages/platform-ui/src/api/modules/graph.ts` → `computeSecretsUnion`; `packages/platform-ui/src/features/secrets/types.ts` → `mapEntryToScreenSecret` (status='missing' when `required && !present`)

### Regression details
- `packages/platform-ui/src/lib/vault/collect.ts` only collects legacy refs and skips canonical refs.
- Canonical refs introduced by backend tooling (e.g., `packages/platform-server/tools/graph-ref-migrate/transform.ts`).
- No Vault SDK/API change required; UI must recognize both legacy and canonical formats.

## Proposed fix
Update `packages/platform-ui/src/lib/vault/collect.ts` to support both legacy and canonical vault reference shapes:
- Continue collecting legacy `{ source:'vault', value: string }`.
- Also collect canonical vault objects:
  - Direct: any object with `kind === 'vault'` and non-empty `mount`, `path`, `key` strings.
  - Nested under `source:'vault'`: `{ source:'vault', value:{ kind:'vault', mount, path, key } }`.
- Normalize canonical refs to `mount/path/key` for downstream parsing.
- Skip canonical refs that omit `mount` to avoid ambiguous matching (assumes migration has populated mount; otherwise consider future enhancement).

## Implementation plan
1. Modify `packages/platform-ui/src/lib/vault/collect.ts`:
   - Add helpers `isRecord` and `toCanonicalVaultString(raw)` returning `mount/path/key` or `null`.
   - Extend visitor logic to collect:
     - Direct canonical objects,
     - `source:'vault'` + canonical values,
     - Existing legacy strings.
   - Preserve Set-based deduplication and recursion.
2. Add unit tests:
   - `packages/platform-ui/src/lib/vault/__tests__/collect.test.ts`: cases for direct canonical and canonical-as-value under `source:'vault'`.
   - `packages/platform-ui/src/lib/vault/__tests__/required.test.ts`: ensure `computeRequiredKeys` returns `SecretKey[]` for canonical refs.
   - Optional: sanity for `useNodeVaultStatus` canonical refs.
3. No changes required in `computeRequiredKeys`, `computeSecretsUnion`, or `discoverVaultKeys`.

## Edge cases
- Canonical refs without `mount` are ignored to avoid guessing; consider enhancement to default if exactly one mount exists (out of scope here).
- Paths/keys must be non-empty; no case folding; stale graph refs will correctly appear as Missing.

## Test plan
- Install and run platform-ui tests: `pnpm i`; `pnpm -w --filter @agyn/platform-ui test`.
- Update/add tests above and confirm they pass.
- Optional manual smoke: run UI and verify Missing badge/count appears for canonical-referenced secrets absent in Vault.

## Definition of done
- Secrets page shows Missing status for secrets referenced in the graph (legacy or canonical) that are absent in Vault.
- All new and existing unit tests pass.
- PR linked to this issue with clear description of changes.

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- normalize canonical vault references in the collector and skip entries without a mount
- cover canonical reference cases in collect/required unit tests
- confirm the Secrets page reports Missing state for canonical refs

## Testing
- pnpm -w --filter @agyn/platform-ui test (91 files, 370 tests passed)

Closes #1189.

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Local Verification
- \Scope: 2 of 6 workspace projects
None of the selected packages has a "lint\" script (no issues)
- \Scope: 2 of 6 workspace projects
None of the selected packages has a "test\" script
  - Test Files: 91 passed (91)
  - Tests: 370 passed (370)
  - Skipped: 0

File: packages/platform-ui/src/lib/vault/collect.ts [hunk 1]
```diff
@@ -4,6 +4,27 @@
 export function collectVaultRefs(input: unknown): string[] {
   const out = new Set<string>();
 
+  function isVaultSource(value: unknown): boolean {
```
Comment (noa-lucent) [inline packages/platform-ui/src/lib/vault/collect.ts:9]: [nit] The header comment still claims we only recognize { source: 'vault', value: string } shapes. Since this function now handles canonical vault refs directly and via source/value pairs, please expand the comment so future readers get an accurate contract.

**Review by noa-lucent — DISMISSED** [review]
Collector handles canonical refs alongside legacy strings, and unit tests cover direct/nested cases plus missing mount/key skips. Left one nit about refreshing the header comment.

File: packages/platform-ui/src/lib/vault/collect.ts (hunk 1 above)
Comment (casey-brooks) [reply packages/platform-ui/src/lib/vault/collect.ts:9]: Header comment updated to cover canonical vault references. Thanks for the catch!

**Review by noa-lucent — APPROVED** [review]
Header comment now accurately describes the supported legacy and canonical shapes. Re-approving.

**Comment by rowan-stein** [comment]
All checks are green and changes are approved by @noa-lucent. Requesting maintainer review from @HautechAI/humans to satisfy branch protection. Auto-merge is enabled; once the required review is in, this PR will merge automatically.

**Review by vitramir — APPROVED** [review]
