### PR TITLE
Fix: make Agent node title editable in Graph sidebar

### LINKED ISSUE #1132: Graph: Cannot edit Agent node title in sidebar
# Graph: Cannot edit Agent node title in sidebar

## Summary
On the Graph screen, the Agent node’s Title field in the right-hand sidebar does not accept typing. The input appears non-editable even though it is rendered.

## Impact
Users cannot rename Agent nodes from the Graph UI, making graphs harder to manage and identify.

## Steps to Reproduce
1. Open the Graph screen.
2. Select an Agent node.
3. In the right sidebar, attempt to type into the "Title" input.
4. Observe that typing does not update the field.

## Expected Behavior
Typing in the Title input should update the Agent node’s title immediately and persist on blur/save.

## Actual Behavior
The Title input remains blank/unchanged and appears non-editable.

## Root Cause (from research)
- Controlled input mismatch: The config object passed to `NodePropertiesSidebar` does not include a usable `title` for Agent nodes unless a non-empty `config.title` already exists. The sidebar’s Title input is controlled by `config.title`; since it’s undefined for Agents, typing triggers updates internally, but the input value never updates, making it look non-editable.

## Proposed Fix
- In `GraphLayout.tsx`, when constructing the sidebar entry/config, set `config.title = config.title ?? selectedNode.title` so the Title input always receives a valid, up-to-date value.

### Affected Files
- `agents/packages/platform-ui/src/components/agents/GraphLayout.tsx`

## Test Plan
Manual verification:
- Select an Agent node and verify the Title input shows the current title (or blank with placeholder) and accepts typing.
- Blur the input and confirm the header display updates accordingly.
- Keyboard behavior: Enter/Escape do not disrupt editing; Backspace/Delete modify the field and do not delete the node while the input is focused.
- Edge cases: Clear the title and blur; confirm default display logic kicks in. Modify name/role fields and ensure placeholder/default logic still behaves correctly.
- Switch selection among nodes; Title reflects each selection’s value.
- If undo/redo exists, verify title changes persist appropriately.

## Additional Notes
- This change does not alter persistence formats; it only fixes the controlled value passed to the sidebar input.

### PR DESCRIPTION
**Pull request by casey-brooks**
## Summary
- ensure the agent sidebar config uses the selected node title when missing to keep the input controlled

Fixes #1132

## Testing
- pnpm --filter @agyn/platform-ui lint
- pnpm --filter @agyn/platform-ui test -- --runInBand
- pnpm dev (startup only; UI verification limited by headless environment)

### CODE REVIEW

**Comment by casey-brooks** [comment]
## Test & Lint Summary
- pnpm --filter @agyn/platform-ui lint ✅
- pnpm --filter @agyn/platform-ui test -- --runInBand ✅ (357 passed, 0 failed, 0 skipped)

**Comment by rowan-stein** [comment]
Requesting review for PR #1135.

Context: Fix for Issue #1132 (Graph: Agent node Title not editable in sidebar).

Summary of change:
- In `packages/platform-ui/src/components/agents/GraphLayout.tsx`, the sidebar config now sets `title = config.title ?? selectedNode.title` so the Title input is controlled by a valid value.

Focus areas:
- Controlled input behavior in the NodePropertiesSidebar (Title field).
- Ensure no regressions in title fallback/default display logic for Agent nodes.
- Keyboard interactions (Delete/Backspace) remain scoped appropriately when typing in the input.

CI/local checks:
- Lint and tests for platform-ui passed locally.

Thanks!

**Review by noa-lucent — DISMISSED** [review]
Looks solid. I validated that the sidebar config now hydrates `config.title` from `selectedNode.title` when the raw config is undefined, which keeps the NodePropertiesSidebar title input controlled and editable. Other node types retain their existing titles and the change stays confined to sidebar data shaping, so there are no observable regressions or keyboard side effects. Thanks for the clear, focused fix.

**Comment by rowan-stein** [comment]
CI is green and the fix is ready. The repository requires CODEOWNERS approval and uses a merge queue.

- Requested review from `HautechAI/humans` (code owners).
- Once approved, we will queue this PR for merge.

Context: Fixes Issue #1132 (Agent node Title not editable in Graph sidebar).

**Comment by rowan-stein** [comment]
Stakeholder acceptance criteria added (see Issue #1132). Please implement and add tests in this PR:

Requirements
1) Title input must display the exact persisted value (empty if empty, filled if filled).
2) If Title is empty, show the computed title as placeholder only.
3) Computed title fallback order:
   - Title (config.title)
   - "<Name> (<Role>)"
   - "Agent"
4) Computed title is used ONLY for graph node labels; all other UIs should use Name and Role directly.

Implementation plan (from research):
- useGraphData.updateNode: when updates.title present, update node.title, node.config.title, and metadataRef.config.title; schedule save (debounced).
- GraphLayout.tsx: do not merge fallback into config.title; sidebar config.title must be the persisted value (empty allowed). Centralize resolveAgentDisplayTitle to apply fallback strictly for the graph label. Stop passing displayTitle into the sidebar.
- NodePropertiesSidebar: Title input value = config.title; placeholder = computeAgentDefaultTitle(name, role, Agent). Sidebar header for Agent should use name/role (not Title).

Tests to add:
- Unit: computeAgentDefaultTitle and resolveAgentDisplayTitle permutations.
- Integration: editing Title persists; clearing Title persists empty and shows placeholder after reload; graph uses computed fallback; non-graph UIs use name/role; keyboard focus behaviors.

Please push updates to branch fix/agent-title-edit. Ensure all tests pass locally before requesting another review.

**Comment by casey-brooks** [comment]
## Summary
- prevent useGraphData.updateNode from dropping config.title during profile-only edits
- ensure agent graph nodes and sidebar keep saved titles or empty placeholders across name/role changes
- add regression coverage for profile updates with non-empty and empty titles plus hook-level unit test

## Testing
- `pnpm --filter @agyn/platform-ui lint`
- `pnpm --filter @agyn/platform-ui test -- --runInBand` (374 passed)

File: packages/platform-ui/src/components/agents/GraphLayout.tsx [hunk 1]
```diff
@@ -804,32 +796,23 @@ export function GraphLayout({ services }: GraphLayoutProps) {
...
-
-    if (rawConfigTitle && rawConfigTitle.trim().length > 0) {
-      config.title = rawConfigTitle;
-    }
-
-    return {
-      config,
-      displayTitle: resolveDisplayTitle(selectedNode),
-    };
   }, [selectedNode]);
```
Comment (noa-lucent) [inline packages/platform-ui/src/components/agents/GraphLayout.tsx:813]: [major] With this change we now depend on `config.title` to drive the controlled value in the sidebar. However `handleConfigChange` still strips the existing title from every config payload unless the incoming patch explicitly contains a `title`. Try the repro: give an agent a custom title, then update only the Name or Role field. We send `updateNode(nodeId, { config: { …without title… } })`, `useGraphData` persists that object back onto the node, and on the next render `configTitle` resolves to `''`, so the Title input goes blank. That violates the "persisted value stays visible" requirement. Please carry the current title through any non-title config updates (e.g. merge the existing `node.config.title`/`node.title` back into the update) and add coverage for this path.

**Review by noa-lucent — CHANGES_REQUESTED** [review]
Thanks for the expanded coverage and for tightening the controlled title flow. I found one regression we need to plug before this can merge—details inline.

**Review by noa-lucent — APPROVED** [review]
Re-tested the regression path: editing an agent’s name/role no longer strips the stored title, and the new unit/integration coverage exercises the save pipeline to guard it going forward. Graph labels, sidebar placeholders, and non-graph displays now follow the expected fallback order. Thanks for the quick turnaround—looks good to ship.

**Review by vitramir — APPROVED** [review]
